name: ganta
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch:pytorch
  - pytorch:torchvision
  - pytorch:torchaudio
  - pytorch:cudatoolkit=10.2
  - conda-forge:opencv
  - python=3
  - numpy
  - scipy
  - matplotlib
  - numba
  - spyder
  - pytest

